ALTER TABLE `users`
ADD COLUMN `firstname` VARCHAR(50) NOT NULL,
ADD COLUMN `lastname` VARCHAR(50) NOT NULL,
ADD COLUMN `dateofbirth` DATE NOT NULL,
ADD COLUMN `sex` VARCHAR(10) NOT NULL,
ADD COLUMN `height` INT NOT NULL,
ADD COLUMN `history` TEXT;
ADD COLUMN `registerFinished` BOOLEAN NOT NULL DEFAULT false;
